#pragma once
#include "CALUMI_Math.h"

//#define SYNC_ONLY_TRANSITION_OUT bool Sync_Only_Transition_Out : 1 = false
//#define MAX_BLEND_TIME float Max_Blend_Time = 0.0f
//
//namespace CALUMI { namespace SFBGS {
//
//	enum class CALUMIANIMATION_API AnimationVariable : uint16_t
//	{
//		NONE,
//		Acceleration,
//		ActiveTurnInPlace,
//		AimAndAttack,
//		AimAtLocation,
//		AimWobble,
//		AimWobbleSpeedMult,
//		Amount,
//		AnimObjActive,
//		AnimSpeed,
//		ArmillaryAssemblePhase1,
//		ArmillaryAssemblePhase2,
//		ArmillaryAssemblePhase3,
//		ArmillaryAssemblePhase4,
//		ArmillaryAssemblePhase5,
//		ArmillaryAssemblePhase6,
//		ArmillaryPhase1,
//		ArmillaryPhase2,
//		ArmillaryPhase3,
//		ArmillaryPhase4,
//		ArmillaryPhase5,
//		ArmillaryPhase6,
//		bAimActive,
//		bAlignWithAimAssistTarget,
//		bAllowFinisher,
//		bAllowReversal,
//		bBlockMeleeBash,
//		bCameraHits,
//		bCanComboAttack,
//		bCanQueueAttackWhileReloading,
//		bChargeRecharging,
//		bCombatWalk,
//		bDelayReloading,
//		bDelayStandStart,
//		bDisableAlert,
//		bDisableFurnitureHeadtrack,
//		bDisableWeaponConstraint,
//		bDoBoltCharge,
//		bDontAllowAttack,
//		bDontAllowBlock,
//		bDontAllowFlinch,
//		bDontAllowPowerAttack,
//		bDontAllowReloading,
//		bDoReloadLoop,
//		bEnableHandIK,
//		bEnableLeftHandIK,
//		bEnableRightHandIK,
//		bFootLeftLock,
//		bFootLeftUnlock,
//		bFootRightLock,
//		bFootRightUnlock,
//		bFreeMovement,
//		bHasAnimObjectVisible,
//		bHeadLightIsVisible,
//		bHeadTrackingActive,
//		bHelmetIsVisible,
//		bHelmetLightIsOn,
//		bInitializeInstant,
//		bInRelaxedPose,
//		bInReloadState,
//		bInReloadStateWithoutSightMode,
//		bIsAttacking,
//		bIsBleedingOut,
//		bIsBlocking,
//		bIsEnteringCover,
//		bIsEquipping,
//		bIsExitingCover,
//		bIsFirstPerson,
//		bIsFurnitureExit,
//		bIsGrazing,
//		bIsHiding,
//		bIsInAir,
//		bIsInCamera,
//		bIsInCover,
//		bIsInLargeFlavor,
//		bIsInScene,
//		bIsLanding,
//		bIsMantling,
//		bIsMelee,
//		bIsMirrored,
//		bIsNotTalking,
//		bIsPathing,
//		bIsPlayerShip,
//		bIsReloading,
//		bIsShuffling,
//		bIsSliding,
//		bIsStaggered,
//		bIsTouchingGround,
//		bIsTunneling,
//		bIsUnequipping,
//		bLadderLeftHandUp,
//		bLandInPlace,
//		bLeftHandCasting,
//		bManualAnimObjUnequip,
//		bNoAdditivePose,
//		bNoAim,
//		bNoAlertAdditive,
//		bNoArmorOffset,
//		bNoFeatherSpine,
//		bNoFlavor,
//		bNoFootIK,
//		bNoHeadTrack,
//		bNoIdleBack,
//		bNoIdleFace,
//		bNoLeftHandIK,
//		bNoRightHandIK,
//		Body_Length, //Body Length
//		BoneWeightsAction,
//		bPairedLead,
//		bPartialBodyInstant,
//		bPlayerMoveStartActive,
//		bPlayReloadEnd,
//		bReloadAborted,
//		bRetainEquipment,
//		bShipPitchDown,
//		bShipPitchUp,
//		bShipRoll,
//		bShipStrafeDown,
//		bShipStrafeLeft,
//		bShipStrafeLR,
//		bShipStrafeRight,
//		bShipStrafeUD,
//		bShipStrafeUp,
//		bShipYawLeft,
//		bShipYawRight,
//		bTailAttack,
//		bUseSequentialReloading,
//		bUseSoaring,
//		bUseStandToExit,
//		bWeaponLeftToLAnimObject,
//		bWeaponLeftToRAnimObject,
//		bWeaponLeftToRAnimObject3,
//		bWeaponToRAnimObject,
//		bZeroGSpine,
//		CameraFOV,
//		CameraNearFar,
//		CameraYawSpeed,
//		CanEnableGunFailsafe,
//		CanStaySightedWhileReloading,
//		Capacity,
//		CapacityPercent,
//		ChestHeadingMax,
//		ChestHeadingMin,
//		cHitReactionBodyPart,
//		cHitReactionDir,
//		CumulativeAnimationsCount,
//		CurrentAmount,
//		CurrentAperture,
//		CurrentGraphState,
//		CurrentPosition,
//		CurrentRotation,
//		CurrentSpeed,
//		DesiredLocation,
//		DirectAt_Heading_Delta, //DirectAt Heading Delta
//		DirectAtHeadingMax,
//		DirectAtHeadingMin,
//		DirectAtHeadingVar,
//		DirectAtPitchMax,
//		DirectAtPitchMin,
//		DirectAtPitchVar,
//		Direction,
//		DirectionSmoothed,
//		DisableAllowRotation,
//		DisableAnimationDriven,
//		DisableHeadingMax,
//		DisableHeadingMin,
//		DistanceToStop,
//		DrawSpeedMult,
//		fActorScale,
//		fActorScaleInverse,
//		fAmmoCountAsTimePercent,
//		fAmmoCountPercentage,
//		fAmmoRemaining,
//		fBlendTime_Combat,
//		fBlendTime_Default,
//		fBlendTime_IdleLocomotionSwitch,
//		fCameraPitch,
//		fCameraYaw,
//		fChargePercentage,
//		fCockpitBoost,
//		fCockpitBrakeThrusters,
//		fCockpitEngineState,
//		fCockpitGForce,
//		fCockpitGravDriveState,
//		fCockpitHorizontalInput,
//		fCockpitHullIntegrityState,
//		fCockpitPitch,
//		fCockpitReactorState,
//		fCockpitRoll,
//		fCockpitShieldState,
//		fCockpitSpeed,
//		fCockpitTargetLock,
//		fCockpitThrottle,
//		fCockpitThrottleInput,
//		fCockpitThrottleReverse,
//		fCockpitThrusters,
//		fCockpitVerticalInput,
//		fCockpitYaw,
//		fControllerMoveXDampen,
//		fControllerMoveXRaw,
//		fControllerMoveYRaw,
//		fControllerMoveZRaw,
//		fControllerXRaw,
//		fControllerXRawDampen,
//		fControllerYRaw,
//		fControllerYRawDampen,
//		fDesiredHeading,
//		fFastWalkSpeed,
//		fFlightHorizontalInput,
//		fFlightMaxSpeed,
//		fFlightPitchInput,
//		fFlightRollInput,
//		fFlightThrottleInput,
//		fFlightVerticalInput,
//		fFlightYawInput,
//		fFXgeneric01,
//		fFXgeneric02,
//		fFXgeneric03,
//		fGravityScale,
//		fGunDownToGunUpDuration,
//		fGunUpToGunDownDuration,
//		fHeadingSpeed,
//		fHintVisibility,
//		fHipRelativeMotion,
//		fImpactDist,
//		fInventoryHeading,
//		fMeterCount,
//		fMeterCountPercentage,
//		fPitchSpeed,
//		fPowerIntensity,
//		fProjectilePower,
//		fRandomClipStartTimePercentage,
//		fRingControl,
//		fRingSpeed,
//		fRingSpeedFast,
//		fRingSpeedMedium,
//		fRingSpeedSlow,
//		fRingSpin,
//		fRingSuccessSpeed,
//		fRingTarget,
//		fShipQuadrant,
//		fThrottleDamp,
//		fTurretHeadingMax,
//		fTurretHeadingMin,
//		fTurretPitchMax,
//		fTurretPitchMin,
//		fVariableRangeAperture,
//		fVariableRangeDistance,
//		GripOffset,
//		HasPower,
//		HeadHeadingMax,
//		HeadHeadingMin,
//		HitReactionTransferVariable,
//		iAmmoCount,
//		iAttackState,
//		iAttackState0,
//		iAttackState1,
//		iAttackState2,
//		iAttackState3,
//		iAttackState4,
//		iAttackState5,
//		iAttackState6,
//		iAttackState7,
//		iCriticalHitType,
//		iIsBlindFiring,
//		iIsGunDown,
//		iIsInSneak,
//		iIsPlayer,
//		iIsPoseB,
//		iIsSighted,
//		iLadderClimbState,
//		iMagazineCapacity,
//		iPartialCover,
//		iPlayerLadderClimbAnimation,
//		iPlayingSprintAnimation,
//		iRigIndex,
//		iRootSwitch,
//		IsCompletelyStopped,
//		iSightedRequested,
//		IsInstantInit,
//		IsNotAligned,
//		IsOn,
//		iStaggerType,
//		iState,
//		IsUsingCodeDrivenRotation,
//		iSwitchingPerspectives,
//		iSyncActions,
//		iSyncActorStance,
//		iSyncBleedout,
//		iSyncCoverStates,
//		iSyncFullbodyActions,
//		iSyncGravDash,
//		iSyncGravity,
//		iSyncGunActions,
//		iSyncIdleLocomotion,
//		iSyncIdleTurnState,
//		iSyncIdleWalkRun,
//		iSyncInDialogueScene,
//		iSyncInjured,
//		iSyncInventoryCamera,
//		iSyncJumpState,
//		iSyncMeleeActions,
//		iSyncMoveDirection,
//		iSyncOnGround,
//		iSyncOpenClose,
//		iSyncPartialBody,
//		iSyncPartialBodyBlend,
//		iSyncPartialBodyState,
//		iSyncPose,
//		iSyncPower,
//		iSyncRelaxedReadyAlert,
//		iSyncRelaxReadySneak,
//		iSyncRightLeft,
//		iSyncSighted,
//		iSyncSprintState,
//		iSyncStandingCrouching,
//		iSyncStateAB,
//		iSyncStunState,
//		iSyncSwimState,
//		iSyncTransitions,
//		iSyncTurnLeft,
//		iSyncTurnRight,
//		iSyncTurnState,
//		iTurnType,
//		iWantBlock,
//		LadderStepDesiredLocation,
//		LockAlignementToCameraDuringTurnAnimation,
//		LookAtDir,
//		LookAtHeadingMax,
//		LookAtHeadingMin,
//		LookAtHeadingVar,
//		LookAtLocation,
//		LookAtPitchMax,
//		LookAtPitchMin,
//		LookAtPitchVar,
//		LookHeading,
//		LookHeadingOffset,
//		MantleEndPos,
//		MantleHeadingOffset,
//		MantleTogether,
//		MeleeAttack_Bite02,
//		NeedPower,
//		NPCHeading,
//		NPCHeadingOffset,
//		OpenCloseFormState,
//		PairedAnimHash,
//		PairedHeadingOffset,
//		PairedTranslationOffset,
//		Pitch,
//		PitchDelta,
//		PitchOffset,
//		PlaybackSpeedMult,
//		PlayPartialBodyStart,
//		Position,
//		ReloadSpeedMult,
//		Rotation,
//		RotationSpeed,
//		SetColorA,
//		SetColorB,
//		SetStateA,
//		SetStateB,
//		ShipPitchDown,
//		ShipPitchUp,
//		ShipRoll,
//		ShipStrafeDown,
//		ShipStrafeLeft,
//		ShipStrafeRight,
//		ShipStrafeUp,
//		ShipYawLeft,
//		ShipYawRight,
//		ShouldUseTurnOnSpotGraph,
//		SightedSpeedMult,
//		SightedTransitionSec,
//		Speed,
//		StaggerDirection,
//		StaggerMagnitude,
//		StartAltIdle,
//		StartsOff,
//		State01Index,
//		State02Index,
//		StateA01Index,
//		StateA02Index,
//		StateB01Index,
//		StateB02Index,
//		SyncJumpBlend,
//		TurnDelta,
//		TurnDeltaSmoothed,
//		TurnOnSpotEnforceDirectAtLimits,
//		UnequipInterruptable,
//		VehicleAirTime,
//		VehicleForwardVelocity,
//		VehicleIsBoosting,
//		VehicleIsVertBoosting,
//		VehicleLateralVelocity,
//		VehicleSpeed,
//		VehicleWheelForwardSlipVelocity,
//		VehicleWheelOnGround,
//		VehicleZVelocity,
//		VelocityZ,
//		VerticalDirection,
//		WeaponAttackAnimationDuration,
//		WeaponSpeedMult,
//		WeaponSpeedMult1,
//		WeaponSpeedMult2,
//
//
//		UNKNOWN = 0xFFFF
//	};
//	enum class CALUMIANIMATION_API AnimationVariableType {Integer = 0, Float = 1, String = 2, Boolean = 3, Vector = 4, Any = 5};
//	CALUMIANIMATION_API const char* AnimationVariableToString(AnimationVariable vType);
//	CALUMIANIMATION_API AnimationVariable AnimationVariableFromString(const char* vStr);
//	CALUMIANIMATION_API AnimationVariableType GetAnimationVariableType(AnimationVariable vType);
//
//	struct CALUMIANIMATION_API intEntry : Utilities::StringContainer
//	{
//		static const AnimationVariableType _type = AnimationVariableType::Integer;
//		intEntry& operator=(int iVal);
//		intEntry& operator=(AnimationVariable iVal);
//		intEntry(AnimationVariable var) : StringContainer(AnimationVariableToString(var)) {}
//		intEntry(int iVal);
//		using StringContainer::operator=;
//		using StringContainer::StringContainer;
//		int GetValueAsType();
//		bool IsValueType();
//	};
//
//	struct CALUMIANIMATION_API floatEntry : Utilities::StringContainer
//	{
//		static const AnimationVariableType _type = AnimationVariableType::Float;
//		floatEntry& operator=(float fVal);
//		floatEntry& operator=(AnimationVariable fVal);
//		floatEntry(AnimationVariable var) : StringContainer(AnimationVariableToString(var)) {}
//		floatEntry(float fVal);
//		using StringContainer::operator=;
//		using StringContainer::StringContainer;
//		float GetValueAsType();
//		bool IsValueType();
//	};
//
//	struct CALUMIANIMATION_API strEntry : Utilities::StringContainer
//	{
//		static const AnimationVariableType _type = AnimationVariableType::String;
//		using StringContainer::StringContainer;
//	};
//
//	struct CALUMIANIMATION_API boolEntry : Utilities::StringContainer
//	{
//		static const AnimationVariableType _type = AnimationVariableType::Boolean;
//		boolEntry& operator=(bool bVal);
//		boolEntry& operator=(AnimationVariable bVal);
//		boolEntry(AnimationVariable var) : StringContainer(AnimationVariableToString(var)) {}
//		boolEntry(bool bVal);
//		using StringContainer::operator=;
//		using StringContainer::StringContainer;
//		bool GetValueAsType();
//		bool IsValueType();
//	};
//
//	struct CALUMIANIMATION_API vectorEntry : Utilities::StringContainer
//	{
//		static const AnimationVariableType _type = AnimationVariableType::Vector;
//		vectorEntry& operator=(const Math::Vector3& v3Val);
//		vectorEntry& operator=(AnimationVariable v3Val);
//		vectorEntry(AnimationVariable var) : StringContainer(AnimationVariableToString(var)) {}
//		vectorEntry(const Math::Vector3& v3Val);
//		using StringContainer::operator=;
//		using StringContainer::StringContainer;
//		Math::Vector3 GetValueAsType();
//		bool IsValueType();
//	};
//
//
//	enum class CALUMIANIMATION_API BlendModeFunction : uint8_t
//	{
//		None,
//		Weight,
//		OneMinusWeight
//	};
//
//	CALUMIANIMATION_API const char* BlendModeFunctionToString(const BlendModeFunction& eVal);
//	CALUMIANIMATION_API BlendModeFunction BlendModeFunctionFromString(const char* str);
//
//	enum class CALUMIANIMATION_API AgxAxis : uint8_t
//	{
//		X = 0,
//		Y = 1,
//		Z = 2
//	};
//
//	CALUMIANIMATION_API const char* AgxAxisToString(const AgxAxis& axis);
//	CALUMIANIMATION_API AgxAxis AgxAxisFromString(const char* str);
//	
//	enum class CALUMIANIMATION_API AnimationEvent : uint16_t
//	{
//		NONE,
//		ActionEnd,
//		ActionInterrupt,
//		Activate,
//		ActivateInstant,
//		ActivationDone,
//		AddRagdollToWorld,
//		AlertStart,
//		AlphaEnd,
//		AlphaStart,
//		AmbushEnter,
//		AmbushEnterInstant,
//		AmbushExit,
//		AnimationComplete,
//		AnimationOff,
//		AnimationOn,
//		AnimFinish,
//		AnimObjDraw,
//		AnimObjHide,
//		AnimObjLoad,
//		AnimObjUnequip,
//		AnimObjUnequipAll,
//		Arrive,
//		AssignVariable,
//		AttackEnd,
//		AttackRelease,
//		AttackStart,
//		AttackState,
//		AttackState2,
//		AttackStateNextAttack,
//		AttackStateReset,
//		AttackStop,
//		BeginCastLeft,
//		BeginWeaponDraw,
//		BeginWeaponSheathe,
//		BetaStart,
//		BetaStop,
//		BleedOutBegin,
//		BleedOutEnd,
//		BleedOutStart,
//		BleedOutStop,
//		BlindFireEnd,
//		BlindFireOverStart,
//		BlindFireStart,
//		BlockHitStart,
//		BlockStart,
//		BlockStop,
//		Blue,
//		BoltChargeStart,
//		BoostAnimFinish,
//		BoostBegin,
//		BoostpackExplode,
//		BoostStop,
//		CameraBack,
//		CameraFront,
//		CameraLeft,
//		CameraOverrideStart,
//		CameraOverrideStop,
//		CameraRight,
//		CameraShake,
//		CancelAbort,
//		CardSwiped,
//		CastEnd,
//		CastSelfStart,
//		CastTargetStart,
//		CharacterGenStart,
//		ChargeDownStart,
//		ChargeHoldStart,
//		CharGenBackground,
//		CharGenBody,
//		CharGenFace,
//		CharGenPresets,
//		CharGenTraits,
//		ChargeRelease,
//		ChargeRelease_LeftArm,
//		ChargeRelease_RightArm,
//		ChargeUpStart,
//		ChargeUpStart_LeftArm,
//		ChargeUpStart_RightArm,
//		ChiStart,
//		ChiStop,
//		Close,
//		Closed,
//		Collect,
//		CollectEmpty,
//		CollectFull,
//		CoverActionsEnd,
//		CoverEnd,
//		CoverExit,
//		CriticalHitEnd,
//		CriticalHitStart,
//		CullBone,
//		CullFurnitureBone,
//		CullWeapons,
//		DataSlateClose,
//		DataSlateDown,
//		DataSlateEnd,
//		DataSlateUp,
//		Deactivation,
//		DeathBegin,
//		DeathBleedout,
//		DeathBoostpackBleedout,
//		DeathBoostpackStart,
//		DeathFurniture,
//		DeathMeleeStart,
//		DeathMovingStart,
//		DeathStart,
//		DeltaStart,
//		DeltaStop,
//		Depart,
//		Deploy,
//		Destruction,
//		DigiPicClose,
//		DisableBumper,
//		DisableCharacterController,
//		disableCollision,
//		Dock,
//		Dock_Bottom,
//		Dock_Nose,
//		Dock_Port,
//		Dock_Starboard,
//		Dock_Top,
//		Docked,
//		DockingBridgeClose,
//		DockingBridgeOpen,
//		DockingFinished,
//		DockStarborn,
//		DodgeBackStart,
//		DodgeLeftStart,
//		DodgeRightStart,
//		Done,
//		DoneQ01,
//		dyn_Activation,
//		DynamicCameraShot,
//		DynamicFlavor,
//		DynamicIdle,
//		DynamicIdleAnimObject,
//		DynamicInstant,
//		DynamicPartialBody,
//		DynamicPartialBodyIdle,
//		DynamicPathing,
//		DynamicPhotomode,
//		DynamicPoseSwitch,
//		DynamicRootEnd,
//		DynamicRootStart,
//		DynamicScene,
//		DynamicSceneHold,
//		DynamicShuffle,
//		DynamicTalk,
//		DynamicTalkLarge,
//		DynamicTalkMedium,
//		DynamicTalkSmall,
//		DynamicThreat,
//		DynamicTransition,
//		DynamicTraversal,
//		DynamicTurn,
//		EarlyExit,
//		EffectSequenceFinish,
//		EjectShellCasing,
//		EnableBumper,
//		EnableCharacterController,
//		enableCollision,
//		End,
//		EndAnim,
//		EndAnimatedCamera,
//		EnterCoverCrouchingLeft,
//		EnterCoverCrouchingRight,
//		EnterCoverStandingLeft,
//		EnterCoverStandingRight,
//		EnterFromStand,
//		EpsilonStart,
//		EpsilonStop,
//		Equip,
//		EtaStart,
//		EvadeLeftStart,
//		EvadeRightStart,
//		EvadeStart,
//		ExitCover,
//		ExitLoopEnd,
//		ExitToDeadStart,
//		ExitToStand,
//		ExitToStandAmbush,
//		EyeTrackingOff,
//		EyeTrackingOn,
//		FaceLightOff,
//		FaceLightOn,
//		FaceLightPowerOff,
//		FaceLightPowerOn,
//		FireAutoStart,
//		FireAutoStart_LeftArm,
//		FireAutoStart_RightArm,
//		FireAutoStart_Tail,
//		FireRelease,
//		FireRelease_LeftArm,
//		FireRelease_RightArm,
//		FireSingleBinaryStart,
//		FireSingleStart,
//		FireSingleStart_LeftArm,
//		FireSingleStart_Mouth1,
//		FireSingleStart_Mouth2,
//		FireSingleStart_RightArm,
//		FireSingleStart_Tail,
//		FlavorEnd,
//		FlinchEnd,
//		FlinchStart,
//		Flying,
//		FootLeft,
//		FootRight,
//		FootSneakLeft,
//		FootSneakRight,
//		FootSprintLeft,
//		FootSprintRight,
//		ForceEquip,
//		ForceFaceLightOff,
//		ForceFaceLightOn,
//		ForceFurnitureExit,
//		ForceWeaponFire,
//		FrontExitToRun,
//		FrontExitToStand,
//		FrontExitToStandAmbush,
//		FrontExitToWalk,
//		FurnitureCameraReset,
//		FurnitureCameraStart,
//		FXAnimFinish,
//		FXCoolantActive,
//		FXIdleOff,
//		FXLightsOff,
//		FXLightsOn,
//		FXMuzzleFlash,
//		FXPlay01,
//		FXPlay02,
//		FXSprayImpactEffect,
//		GammaStart,
//		GammaStop,
//		GetUp,
//		GetUpEnd,
//		GetUpStart,
//		gra,
//		GravDashStart_Long,
//		GravDashStart_Medium,
//		GravDashStart_Short,
//		GravityOff,
//		GravityOn,
//		GravJumpCancel,
//		GravJumpExecute,
//		GravJumpFinish,
//		GravJumpInitiate,
//		GrazeEnd,
//		GrazeStart,
//		GrazeStop,
//		Green,
//		GunDownInterrupted,
//		GunDownStart,
//		GunDownStop,
//		HalfClose01,
//		HalfClose02,
//		HalfOpen01,
//		HalfOpen02,
//		HandIKOff,
//		HandIKOn,
//		HeadLightPowerOff,
//		HeadLightPowerOn,
//		HeadTrackingOff,
//		HeadTrackingOn,
//		HelmetLightOff,
//		HelmetLightOn,
//		HelmetLightPowerOff,
//		HelmetLightPowerOn,
//		HideEnd,
//		HideStart,
//		HideStop,
//		HideSubsegment,
//		HitFrame,
//		IdleArmCrossedEquip,
//		IdleArtifactEquip,
//		IdleBackTimer,
//		IdleBedSleeping,
//		IdleBriefcaseEquip,
//		IdleChairGetUp,
//		IdleChairSitting,
//		IdleCoffeeCupEquip,
//		IdleCount,
//		IdleCowerStart,
//		IdleDataSlateEquip,
//		IdleDataSlateReceiveAndReadEquip,
//		IdleDialogueAdditive,
//		IdleDigiPicEquip,
//		IdleDuffleBagEquip,
//		IdleFaceTimer,
//		IdleFlavor,
//		IdleFlavorAdditive,
//		IdleFlavorLarge,
//		IdleFlavorLargeEnd,
//		IdleFlavorNPC,
//		IdleFlavorPartialBody,
//		IdleFlavorPlayer,
//		IdleGiveWatchStart,
//		IdleHandCuffedEquip,
//		IdleHandsBehindEquip,
//		IdleInterrupt,
//		IdlePartialBodyEnd,
//		IdlePartialBodyStop,
//		IdlePartialBodyStopInstant,
//		IdlePartialBodySwitch,
//		IdleQuantumCalibratorEquip,
//		IdleShoppingBagEquip,
//		IdleSitting,
//		IdleStart,
//		IdleStop,
//		IdleSurrenderEquip,
//		IdleSyncStart,
//		IdleSyncStop,
//		IdleTaunt,
//		IdleTechReader2handsBulkyEquip,
//		IdleTechReader2handsEquip,
//		IdleTechReaderEquip,
//		IdleWoundedEquip,
//		InitializeCharGen,
//		InitializeGunGraph,
//		InitializeInventory,
//		InitializeMeleeGraph,
//		InitializeMTGraph,
//		InjuredBegin,
//		InjuredEnd,
//		InjuredStart,
//		InjuredStop,
//		InstantInitializeCharGen,
//		InstantInitializeGunGraph,
//		InstantInitializeInventory,
//		InstantInitializeMeleeGraph,
//		InstantInitializeMTGraph,
//		InstantInitializeUnconscious,
//		InterpolationMark,
//		InventoryCameraBack,
//		InventoryCameraBody,
//		InventoryCameraFaceGen,
//		InventoryCameraHead,
//		InventoryCameraMain,
//		InventoryCameraOutfit,
//		InventoryCameraWeapon,
//		InventoryOpen,
//		InventoryOpenDraw,
//		InvertMirror,
//		InvertMirrorAndCrouch,
//		IotaStart,
//		IotaStop,
//		IsOff,
//		IsOn,
//		JiggleEvaluate,
//		JigglePitchDown,
//		JigglePitchUp,
//		JiggleRollLeft,
//		JiggleRollRight,
//		JiggleYawLeft,
//		JiggleYawRight,
//		JumpBoost,
//		JumpBoostBegin,
//		JumpDown,
//		JumpFall,
//		JumpIdle01,
//		JumpIdle02,
//		JumpLand,
//		JumpLandAdditive,
//		JumpLandStop,
//		JumpStart,
//		JumpTraversal,
//		JumpTraversalLand,
//		JumpUp,
//		JunoReset,
//		KappaStart,
//		KappaStop,
//		KillActor,
//		KnockDownStart,
//		LadderClimb,
//		LadderClimbDown,
//		LadderClimbIdle,
//		LadderClimbLeftHandUp,
//		LadderClimbRightHandUp,
//		LadderClimbUp,
//		LadderEnd,
//		LadderEnterClimbDown,
//		LadderEnterClimbUp,
//		LadderExit,
//		LadderLeftHandUp,
//		LadderRightHandUp,
//		LambdaStart,
//		LambdaStop,
//		Land,
//		Landed,
//		LandedClosed,
//		LandedSlave,
//		LandingFinished,
//		LandingFinishedFailsafe,
//		LandingKreet,
//		LandingKreetPirates,
//		LandKreetSlave,
//		LandLarge,
//		LandNPC,
//		LandSlave,
//		LandSlaveNPC,
//		LandStarborn,
//		LandStarbornNPC,
//		LandVertical,
//		LeftExitToRun,
//		LeftExitToStand,
//		LeftExitToWalk,
//		LeftQuickExitToStand,
//		LimbCrippleStart,
//		Link,
//		LoadFurnitureGraph,
//		LoadGunAssemblyGraph,
//		Loop01,
//		LoopCCW01,
//		LoopCW01,
//		MainTrack,
//		MantleCancel,
//		MantleEnd,
//		MantleHands,
//		MantleStart,
//		MaxCumulativeAnimationsReached,
//		MeleeAttack_1,
//		MeleeAttack_2,
//		MeleeAttack_3,
//		MeleeAttack_4,
//		MeleeAttack_5,
//		MeleeAttack_A,
//		MeleeAttack_B,
//		MeleeAttack_Bite01,
//		MeleeAttack_Bite02,
//		MeleeAttack_Bite03,
//		MeleeAttack_Claw01,
//		MeleeAttack_Claw02,
//		MeleeAttack_Head01,
//		MeleeAttack_Head02,
//		MeleeAttack_Head03,
//		MeleeAttack_Left180,
//		MeleeAttack_Left90,
//		MeleeAttack_LeftArm,
//		MeleeAttack_Right180,
//		MeleeAttack_Right90,
//		MeleeAttack_RightArm,
//		MeleeAttack_RightClaw01,
//		MeleeAttack_Tail01,
//		MeleeAttack_Tail02,
//		MeleeAttack01,
//		MeleeAttack02,
//		MeleeAttack03,
//		MeleeAttack04,
//		MeleeAttack05,
//		MeleeAttackBashMiss,
//		MeleeAttackBashStart,
//		MeleeAttackFinisherStart,
//		MeleeAttackPower_1,
//		MeleeAttackPower_2,
//		MeleeAttackPower_B,
//		MeleeAttackPower_Bite01,
//		MeleeAttackPower_Bite02,
//		MeleeAttackPower_Claw01,
//		MeleeAttackPower_Head01,
//		MeleeAttackPower_Tail01,
//		MeleeAttackPower01,
//		MeleeAttackPower02,
//		MeleeAttackPowerStart,
//		MeleeAttackPowerStartZeroG,
//		MeleeAttackSprintStart,
//		MeleeAttackStart,
//		MeleeAttackStartInAir,
//		MeleeAttackStartZeroG,
//		MeleePowerAttack_Forward,
//		MeleePowerAttack_ForwardSlam,
//		MinigameEnd,
//		MinigameStart,
//		MuStart,
//		MuStop,
//		NuStart,
//		NuStop,
//		OffRamp,
//		OmegaStart,
//		OmegaStop,
//		OmicronStart,
//		OmicronStop,
//		OnReloadExit,
//		Open,
//		Opened,
//		Orange,
//		pa_KnifeAttack,
//		pa_TerrormorphBiteHead,
//		pa_TerrormorphBiteHead01,
//		pa_TerrormorphBiteHead02,
//		pa_TerrormorphSlamHead01,
//		pa_TerrormorphSlamHead02,
//		PairedStop,
//		ParasiteFXStart,
//		PartialBodyAnimObjUnequip,
//		PartialCoverStart,
//		PathingBegin,
//		PathingEnd,
//		PathTweenerEnd,
//		PathTweenerEndTween,
//		PathTweenerStart,
//		PhiStart,
//		PhiStop,
//		PhotoMode_Boxer,
//		PhotoMode_Cower,
//		PhotoMode_Gift,
//		PhotoMode_HandsOnHips,
//		PhotoMode_Hero,
//		PhotoMode_Jump,
//		PhotoMode_Kneeling,
//		PhotoMode_LookUp,
//		PhotoMode_Love,
//		PhotoMode_Propose,
//		PhotoMode_SitOnGround,
//		PhotoMode_Sneak,
//		PhotoMode_ThumbsUp,
//		PhotoMode_Wave,
//		PhotoMode_WhatsUp,
//		PhotoModeExit,
//		PickNewIdle,
//		PipboyClosed,
//		PipboyOpened,
//		PiStart,
//		PiStop,
//		PitchOverrideEnd,
//		PitchOverrideStart,
//		Play01,
//		Play02,
//		Play03,
//		Play04,
//		Play05,
//		Play06,
//		PlayerTerminalEnter,
//		PlayerTerminalExit,
//		PlayImod,
//		PlayLandedFX,
//		PlayLandingCamera,
//		PlayLandingEngineFX,
//		PlayLandingEngineFXStatic,
//		PlayLandingFX,
//		PlayReaction01,
//		PlayReaction02,
//		PlayReaction03,
//		PlayReaction04,
//		PlayReaction05,
//		PlayTakeOffCamera,
//		PlayTakeOffFX,
//		PopToClose,
//		PopToOpen,
//		PositionChange,
//		Powered,
//		PreHitFrame,
//		PsiStart,
//		PsiStop,
//		QuickExitToStand,
//		RampClose,
//		RampOpen,
//		ReactionEnd,
//		ReactionStart,
//		ReactionStop,
//		ReadyStart,
//		ReadyState,
//		RearExitToRun,
//		RearExitToStand,
//		RearExitToWalk,
//		RearQuickExitToStand,
//		Recoil_LeftArm,
//		Recoil_RightArm,
//		RecoilStart,
//		Red,
//		ReevaluateGraphState,
//		RelaxedStart,
//		ReloadAbort,
//		ReloadBegin,
//		ReloadComplete,
//		ReloadExit,
//		ReloadLoopStart,
//		ReloadStart,
//		ReloadState,
//		ReloadTacticalStart,
//		RemoveCharacterControllerFromWorld,
//		Reset,
//		ResetCumulative,
//		ResurrectStart,
//		RhoStart,
//		RhoStop,
//		RightExitToRun,
//		RightExitToStand,
//		RightExitToWalk,
//		RightQuickExitToStand,
//		RingInner_CCW,
//		RingInner_CW,
//		RingInner_Success,
//		RingMiddle_CCW,
//		RingMiddle_CW,
//		RingMiddle_Success,
//		RingOuter_CCW,
//		RingOuter_CW,
//		RingOuter_Success,
//		RootAnimOffStart,
//		RootAnimOffStop,
//		Rotate_Long,
//		Rotate_Long01,
//		Rotate_Short,
//		Rotate_Short01,
//		Rotate_Single,
//		Rotate_Single01,
//		RotateCCW_Loop,
//		RotateCCW_Loop01,
//		RotateCW_Loop,
//		RotateCW_Loop01,
//		RotateCW_Single01,
//		RotateSimple01,
//		RunAction,
//		RunStart,
//		SceneAnimationDoneHandler,
//		SceneEnd,
//		SceneNextEvent,
//		SceneNextPhase,
//		SceneStart,
//		SceneStop,
//		SequenceA01,
//		SequenceA02,
//		SequenceA03,
//		SequenceA04,
//		SequenceA05,
//		SequenceA06,
//		SequenceA07,
//		SequenceB01,
//		SequenceB02,
//		SequenceB03,
//		SequenceB04,
//		SequenceB05,
//		SequenceB06,
//		SequenceB07,
//		SetOrientBegin,
//		SetOrientEnd,
//		SetPosBegin,
//		SetPosEnd,
//		SetupGraphRagdoll,
//		ShipImpactStart,
//		ShowSubsegment,
//		ShuffleBackward,
//		ShuffleEnd,
//		ShuffleForward,
//		SightedEnd,
//		SightedOverLowStart,
//		SightedOverStart,
//		SightedStart,
//		SightedState,
//		SightedStop,
//		SightedStopRequest,
//		SigmaStart,
//		sitStartFromStand,
//		sitStartFromStandInstant,
//		sitStartFrontFromStand,
//		sitStartFrontFromStandInstant,
//		sitStartFrontFromWalk,
//		sitStartLeftFromStand,
//		sitStartLeftFromStandInstant,
//		sitStartLeftFromWalk,
//		sitStartRearFromStand,
//		sitStartRearFromStandInstant,
//		sitStartRearFromWalk,
//		sitStartRightFromStand,
//		sitStartRightFromStandInstant,
//		sitStartRightFromWalk,
//		SlavedIdle,
//		SlavedIdleFlavor,
//		SlavedIdleFlavor01,
//		SlavedIdleFlavor02,
//		SlavedIdleFlavor03,
//		SlavedIdleFlavor04,
//		SlavedIdleFlavor05,
//		SlavedIdleFlavor06,
//		SlavedIdleFlavor07,
//		SlavedIdleFlavor08,
//		SlavedIdleFlavor09,
//		Slide,
//		SlideStart,
//		SneakStart,
//		SneakState,
//		SneakStop,
//		SoarStart,
//		SoarStop,
//		SoundPlay,
//		SoundPlayAt,
//		SoundStop,
//		SpellFireLeftHand,
//		SpellFireRightHand,
//		SprintEnd,
//		SprintStart,
//		SprintStartEnd,
//		SprintStop,
//		Stage_2, //"Stage 2"
//		Stage01_Loop,
//		Stage01_Off,
//		Stage01_On,
//		Stage01_Start,
//		Stage01_Stop,
//		Stage02_Loop,
//		Stage02_Off,
//		Stage02_On,
//		Stage02_Start,
//		Stage02_Stop,
//		Stage03_Loop,
//		Stage03_Off,
//		Stage03_On,
//		Stage03_Start,
//		Stage03_Stop,
//		Stage04_Loop,
//		Stage04_Off,
//		Stage04_On,
//		Stage04_Start,
//		Stage04_Stop,
//		Stage05_Loop,
//		Stage05_Off,
//		Stage05_On,
//		Stage05_Start,
//		Stage05_Stop,
//		Stage1,
//		Stage1NoTransition,
//		Stage2,
//		Stage2NoTransition,
//		Stage3,
//		Stage3NoTransition,
//		Stage4,
//		Stage4NoTransition,
//		StaggerEnd,
//		StaggerStart,
//		StaggerStop,
//		StandStart,
//		startAmbushSeq,
//		StartAnimatedCamera,
//		StartAnimatedCameraDelta,
//		StartedWalking,
//		startFloating,
//		StartImpactFX,
//		StartMeleeAttack,
//		startRoar,
//		StartSighted,
//		StartVoice,
//		StateA_Idle,
//		StateA_Play,
//		StateB_Idle,
//		StateB_Play,
//		StateC_Idle,
//		StateC_Play,
//		StateD_Idle,
//		StateD_Play,
//		Stop,
//		Stop01,
//		StopAttackQueuingWhileReloading,
//		StopEffect,
//		stopFloating,
//		StopImod,
//		StopIMod,
//		StopImpactFX,
//		StoppedWalking,
//		StopSighted,
//		StunEnd,
//		StunStart,
//		StunStop,
//		SupportAttackQueuingWhileReloading,
//		SwimStart,
//		SwimStart_Gun,
//		SwimStart_Melee,
//		SwimStop,
//		SyncDeferDeath,
//		SyncLeftFoot,
//		SyncRightFoot,
//		TakeOff,
//		TakeOff_Neon,
//		TakeOffE3,
//		TakeOffFinished,
//		TakeOffNPC,
//		TakeOffSlave,
//		TakeOffStarborn,
//		TakeOffStarbornNPC,
//		TakeOffVertical,
//		TauStart,
//		TauStop,
//		TerminateGraphRagdoll,
//		TerrormorphRevealAnkylosaurusStart,
//		TerrormorphRevealStart,
//		terrormorphSmash,
//		TerrormorphTransformationStart,
//		test,
//		ThetaStart,
//		ThetaStop,
//		ThrowGrenadeStart,
//		ThrowInterrupt,
//		ThrowMineStart,
//		to_PoseA,
//		to_PoseB,
//		to_PoseC,
//		to_ShipDamageState01,
//		to_ShipDamageState02,
//		to_ShipFullHealth,
//		to_ShipFullyDamagedEngine,
//		to_ShipPartialHealthEngine,
//		Trans01,
//		Trans02,
//		Trans03,
//		Trans04,
//		TransitionComplete,
//		TransitionStart,
//		TransitionStop,
//		TraversalFinished,
//		TraversalStart,
//		TraversalStepDone,
//		TraversalStop,
//		TunnelingExit,
//		TunnelStart,
//		TunnelStop,
//		TurnColorBlue,
//		TurnColorDefault,
//		TurnColorGreen,
//		TurnColorOrange,
//		TurnColorRed,
//		TurnColorViolet,
//		TurnColorWhite,
//		TurnColorYellow,
//		TurnLeft,
//		TurnOff,
//		TurnOffFull,
//		TurnOn,
//		TurnOnFlicker,
//		TurnOnFull,
//		TurnOnPulse,
//		TurnOnPulseFast,
//		TurnOnPulseFlicker,
//		TurnOnPulseSlow,
//		TurnRight,
//		TurnStateDefault,
//		TurnStop,
//		Unassemble,
//		UnconsciousStart,
//		UnconsciousStop,
//		UncullBone,
//		UnCullFurnitureBone,
//		UncullWeapons,
//		UnDock,
//		Undock_Bottom,
//		Undock_Nose,
//		Undock_Port,
//		Undock_Starboard,
//		Undock_Top,
//		UndockingFinished,
//		UndockStarborn,
//		Unequip,
//		UnequipComplete,
//		UnequipInterrupted,
//		UnequipInterrupted_Death,
//		Unlink,
//		Unlock,
//		Unpowered,
//		UpsilonStart,
//		UpsilonStop,
//		UseStimpak,
//		VehicleDeath,
//		VehicleForwardCollisionHard,
//		VehicleIdleStart,
//		VehicleIdleStop,
//		VehicleJumpLand,
//		VehicleJumpStart,
//		VideoOnly_Shot11,
//		VideoOnly_Shot12,
//		VideoOnly_Shot13,
//		VideoOnly_Shot14,
//		VideoOnly_Shot15,
//		VideoOnly_Shot21,
//		VideoOnly_Shot21b,
//		Violet,
//		WalkStart,
//		WeaponAttach,
//		WeaponDraw,
//		WeaponFire,
//		WeaponFireEnd,
//		WeaponFireStart,
//		WeaponSheathe,
//		WeaponSheatheInterrupt,
//		WeaponSwing,
//		White,
//		XiStart,
//		XiStop,
//		Yellow,
//		ZeroOutCameraPitch,
//		ZetaStart,
//		ZetaStop,
//
//		//END XTBL EVENTS
//		AdditiveEnd,
//
//		UNKNOWN = 0xFFFF
//	};
//	
//	CALUMIANIMATION_API const char* AnimationEventToString(AnimationEvent event);
//	CALUMIANIMATION_API AnimationEvent AnimationEventFromString(const char* eventStr);
//
//	struct CALUMIANIMATION_API EventEntry : Utilities::StringContainer
//	{
//		static const int _type = 2;
//		EventEntry(AnimationEvent event) : StringContainer(AnimationEventToString(event)) {}
//		EventEntry& operator=(const AnimationEvent& eValue);
//		EventEntry& operator=(unsigned int iValue);
//		using StringContainer::StringContainer;
//
//		AnimationEvent Enum() const;
//	};
//
//	enum class CALUMIANIMATION_API AnimationSyncType : uint8_t
//	{
//		NONE,
//		SyncBoltCharge,
//		SyncCastPower,
//		SyncChargeDown,
//		SyncChargeHold,
//		SyncChargeUp,
//		SyncEnterFurniture,
//		SyncEquip,
//		SyncFireAuto,
//		SyncFireSingle,
//		SyncFootsteps,
//		SyncGunActions,
//		SyncIdle,
//		SyncJumpBoost,
//		SyncJumpFall,
//		SyncJumpFallLoop,
//		SyncJumpLand,
//		SyncJumpLandCamera,
//		SyncJumpStart,
//		SyncMeleeAttack,
//		SyncMeleeAttackPower,
//		SyncReload,
//		SyncReloadEnd,
//		SyncReloadLoop,
//		SyncSlide,
//		SyncStandToRun,
//		SyncThrowGrenade,
//		SyncThrowMine,
//		SyncTurning,
//		SyncUnequip,
//
//
//		UNKNOWN = 0xFF
//
//	};
//
//	CALUMIANIMATION_API const char* AnimationSyncTypeToString(AnimationSyncType sType);
//	CALUMIANIMATION_API AnimationSyncType AnimationSyncTypeFromString(const char* sTypeStr);
//
//	struct CALUMIANIMATION_API SyncEntry : Utilities::StringContainer
//	{
//		static const int _type = 2;
//		SyncEntry(AnimationSyncType type) : StringContainer(AnimationSyncTypeToString(type)) {}
//		SyncEntry& operator=(const AnimationSyncType& eValue);
//		SyncEntry& operator=(unsigned int iValue);
//		using StringContainer::StringContainer;
//
//		AnimationSyncType Enum() const;
//	};
//
//	struct CALUMIANIMATION_API EventIOComponent
//	{
//		bool Non_Instanced : 1 = false;
//		EventEntry Event;
//		strEntry Payload;
//
//		EventIOComponent() = default;
//		EventIOComponent(bool Non_Instanced, const EventEntry& Event, const strEntry& Payload)
//			: Non_Instanced(Non_Instanced), Event(Event), Payload(Payload){}
//
//		bool operator==(const EventIOComponent& other) const;
//		bool operator!=(const EventIOComponent& other) const;
//	};
//
//	struct CALUMIANIMATION_API ImpactTag
//	{
//		enum class ImpactSize { Small, Medium, Large };
//		strEntry Tag_Name;
//		strEntry Body_Part;
//		ImpactSize Impact = ImpactSize::Small;
//
//		ImpactTag() = default;
//		ImpactTag(const strEntry& Tag_Name, const strEntry& Body_Part, const ImpactSize& Impact)
//			: Tag_Name(Tag_Name), Body_Part(Body_Part), Impact(Impact)
//		{
//		}
//
//		bool operator==(const ImpactTag& other) const;
//		bool operator!=(const ImpactTag& other) const;
//	};
//
//	struct CALUMIANIMATION_API iStatePair
//	{
//		strEntry iState_Name = "UNDEFINED_ISTATE";
//		int iState_Value = 0;
//
//		iStatePair() = default;
//		iStatePair(const strEntry& iState_Name, int iState_Value)
//			: iState_Name(iState_Name), iState_Value(iState_Value)
//		{
//		}
//
//	};
//
//	struct CALUMIANIMATION_API VariableAssignmentComponent
//	{
//		AnimationVariable Variable_Name = AnimationVariable::NONE;
//	private:
//		Utilities::StringContainer Value = "";
//		AnimationVariableType _Type = AnimationVariableType::Any;
//	public:
//		const char* GetValue() const;
//		AnimationVariableType GetVariableType() const;
//		VariableAssignmentComponent() = default;
//		VariableAssignmentComponent(const AnimationVariable& Variable_Name, const Utilities::StringContainer& Value);
//		void Assign(AnimationVariable vName, const char* sVal);
//		void Assign(const char* sVal);
//		
//	};
//
//	struct CALUMIANIMATION_API BlendComponent
//	{
//		bool SM_Evt : 1 = false;
//		float Param = 0.0f;
//		Utilities::VectorContainer<EventEntry> Enable_Events;
//		Utilities::VectorContainer<EventEntry> Disable_Events;
//	};
//
//}}
//
//
//#pragma warning(disable: 4661)
//template struct CALUMIANIMATION_API CALUMI::Utilities::VectorContainer<CALUMI::SFBGS::EventIOComponent>;
//template struct CALUMIANIMATION_API CALUMI::Utilities::VectorContainer<CALUMI::SFBGS::ImpactTag>;
//template struct CALUMIANIMATION_API CALUMI::Utilities::VectorContainer<CALUMI::SFBGS::iStatePair>;
//template struct CALUMIANIMATION_API CALUMI::Utilities::VectorContainer<CALUMI::SFBGS::VariableAssignmentComponent>;
//#pragma warning(default: 4661)