name: Multi-Platform Build
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config: [debug, release]
        include:
          - os: ubuntu-latest
            preset-prefix: "linux"
          - os: windows-latest
            preset-prefix: "win"
          - os: macos-latest
            preset-prefix: "mac"

    steps:
      - name: Checkout Code
        uses: [actions/checkout@v4](https://github.com/actions/checkout)

      - name: Install Ninja (Optional)
        if: runner.os != 'Windows'
        run: sudo apt-get install ninja-build || brew install ninja

      - name: Configure CMake
        run: >
          cmake -S CALUMI.Animation/ 
          --preset ${{ matrix.preset-prefix }}-${{ matrix.config }}

      - name: Build
        run: cmake -S CALUMI.Animation/ --build --preset ${{ matrix.preset-prefix }}-${{ matrix.config }}
