name: Multi-Platform Build
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config: [debug, release]
        include:
          - os: ubuntu-latest
            preset-prefix: "linux"
            arch: x64
          - os: windows-latest
            preset-prefix: "win"
            arch: x64
          - os: macos-latest
            preset-prefix: "mac"
            arch: arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Ninja (Optional)
        if: runner.os != 'Windows'
        run: sudo apt-get install ninja-build || brew install ninja

      - name: Setup MSVC (Windows Only)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup GCC 14
        if: runner.os == 'Linux'
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 14
          platform: x64

      - name: Configure Library
        working-directory: ./CALUMI.Animation
        run: cmake --preset ${{ matrix.preset-prefix }}-${{ matrix.config }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} 

      - name: Build Library
        working-directory: ./CALUMI.Animation
        run: cmake --build --preset ${{ matrix.preset-prefix }}-${{ matrix.config }} --config ${{ matrix.config }}

      - name: Configure GTests
        working-directory: ./CALUMI.Animation.GTests
        run: cmake --preset ${{ matrix.preset-prefix }}-${{ matrix.config }}-gtests -DCMAKE_BUILD_TYPE=${{ matrix.config }} 

      - name: Print Dir
        run: ls -R

      - name: Build GTests
        working-directory: ./CALUMI.Animation.GTests
        run: cmake --build --preset ${{ matrix.preset-prefix }}-${{ matrix.config }}-gtests --config ${{ matrix.config }}

      - name: Run GTests
        working-directory: ./CALUMI.Animation.GTests
        run: ${{ matrix.preset-prefix }}-${{ matrix.config }}-gtests/run_tests